spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username:  ${EMAIL_USER}
    password: ${EMAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp
