spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: sbrata341@gmail.com
    password: slvaindachyepndc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp
